# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ac96507fc63d228ae541f8af87af782ee931b05a2a1ff9ca2a5619fb0184b4a163e752e883938c865144ee2951e8c16463a71f1006164405b50aaed401c84f

test:
  secret_key_base: cf633ef22a77561b2f3ddc677af937c09df324ffa8b16edf6245eda441c0289ededf582d9806099a9cbaaf054af7fb59700c3c46367f39e1d29c4550d1993416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
